import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Graph } from "./graph.js";
import type { GodNode } from "./types.js";

export function safeFilename(name: string): string {
  const s = name.replaceAll("/", "-").replaceAll(" ", "_").replaceAll(":", "-").replace(/[<>:"/\\|?*]/g, "_").replace(/[. ]+$/g, "");
  return (s || "unnamed").slice(0, 200);
}

function crossCommunityLinks(graph: Graph, nodes: string[], ownCid: number, labels: Record<number, string>): Array<[string, number]> {
  const counts = new Map<string, number>();
  for (const nodeId of nodes) {
    for (const neighbor of graph.neighbors(nodeId)) {
      const cid = graph.nodes.get(neighbor)?.community;
      if (cid !== undefined && cid !== ownCid) {
        const label = labels[Number(cid)] ?? `Community ${cid}`;
        counts.set(label, (counts.get(label) ?? 0) + 1);
      }
    }
  }
  return Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
}

function communityArticle(graph: Graph, cid: number, nodes: string[], label: string, labels: Record<number, string>, cohesion?: number): string {
  const topNodes = nodes.slice().sort((a, b) => graph.degree(b) - graph.degree(a)).slice(0, 25);
  const cross = crossCommunityLinks(graph, nodes, cid, labels);
  const confCounts = new Map<string, number>();
  for (const nodeId of nodes) {
    for (const neighbor of graph.neighbors(nodeId)) {
      const edge = graph.edgeBetween(nodeId, neighbor);
      const conf = edge?.confidence ?? "EXTRACTED";
      confCounts.set(conf, (confCounts.get(conf) ?? 0) + 1);
    }
  }
  const totalEdges = Array.from(confCounts.values()).reduce((sum, n) => sum + n, 0) || 1;
  const sources = Array.from(new Set(nodes.map((node) => String(graph.nodes.get(node)?.source_file ?? "")).filter(Boolean))).sort();
  const lines = [`# ${label}`, "", `> ${nodes.length} nodes${cohesion !== undefined ? ` · cohesion ${cohesion.toFixed(2)}` : ""}`, "", "## Key Concepts", ""];
  for (const nodeId of topNodes) {
    const node = graph.nodes.get(nodeId);
    lines.push(`- **${node?.label ?? nodeId}** (${graph.degree(nodeId)} connections)${node?.source_file ? ` — \`${node.source_file}\`` : ""}`);
  }
  if (nodes.length > topNodes.length) lines.push(`- *... and ${nodes.length - topNodes.length} more nodes in this community*`);
  lines.push("", "## Relationships", "");
  if (cross.length) for (const [other, count] of cross.slice(0, 12)) lines.push(`- [[${other}]] (${count} shared connections)`);
  else lines.push("- No strong cross-community connections detected");
  if (sources.length) lines.push("", "## Source Files", "", ...sources.slice(0, 20).map((src) => `- \`${src}\``));
  lines.push("", "## Audit Trail", "");
  for (const conf of ["EXTRACTED", "STATIC_RESOLVED", "INFERRED", "AMBIGUOUS"]) {
    const n = confCounts.get(conf) ?? 0;
    lines.push(`- ${conf}: ${n} (${Math.round((n / totalEdges) * 100)}%)`);
  }
  lines.push("", "---", "", "*Part of the graphify knowledge wiki. See [[index]] to navigate.*");
  return lines.join("\n");
}

function godNodeArticle(graph: Graph, nodeId: string, labels: Record<number, string>): string {
  const node = graph.nodes.get(nodeId);
  const cid = node?.community;
  const communityName = cid !== undefined ? labels[Number(cid)] ?? `Community ${cid}` : null;
  const byRelation = new Map<string, string[]>();
  for (const neighbor of graph.neighbors(nodeId).sort((a, b) => graph.degree(b) - graph.degree(a))) {
    const edge = graph.edgeBetween(nodeId, neighbor);
    const rel = edge?.relation ?? "related";
    const target = graph.nodes.get(neighbor)?.label ?? neighbor;
    byRelation.set(rel, [...(byRelation.get(rel) ?? []), `[[${target}]]${edge?.confidence ? ` \`${edge.confidence}\`` : ""}`]);
  }
  const lines = [`# ${node?.label ?? nodeId}`, "", `> God node · ${graph.degree(nodeId)} connections · \`${node?.source_file ?? ""}\``, ""];
  if (communityName) lines.push(`**Community:** [[${communityName}]]`, "");
  lines.push("## Connections by Relation", "");
  for (const [rel, targets] of Array.from(byRelation.entries()).sort()) {
    lines.push(`### ${rel}`);
    lines.push(...targets.slice(0, 20).map((target) => `- ${target}`), "");
  }
  lines.push("---", "", "*Part of the graphify knowledge wiki. See [[index]] to navigate.*");
  return lines.join("\n");
}

function indexMarkdown(communities: Record<number, string[]>, labels: Record<number, string>, gods: GodNode[], totalNodes: number, totalEdges: number): string {
  const lines = [
    "# Knowledge Graph Index",
    "",
    "> Auto-generated by graphify. Start here — read community articles for context, then drill into god nodes for detail.",
    "",
    `**${totalNodes} nodes · ${totalEdges} edges · ${Object.keys(communities).length} communities**`,
    "",
    "---",
    "",
    "## Communities",
    "(sorted by size, largest first)",
    ""
  ];
  for (const [cid, nodes] of Object.entries(communities).sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`- [[${labels[Number(cid)] ?? `Community ${cid}`}]] — ${nodes.length} nodes`);
  }
  if (gods.length) {
    lines.push("", "## God Nodes", "(most connected concepts — the load-bearing abstractions)", "");
    for (const god of gods) lines.push(`- [[${god.label}]] — ${god.degree} connections`);
  }
  lines.push("", "---", "", "*Generated by graphify*");
  return lines.join("\n");
}

export async function toWiki(
  graph: Graph,
  communities: Record<number, string[]>,
  outputDir: string,
  options: { communityLabels?: Record<number, string>; cohesion?: Record<number, number>; godNodes?: GodNode[] } = {}
): Promise<number> {
  await mkdir(outputDir, { recursive: true });
  for (const name of await readdir(outputDir).catch(() => [])) if (name.endsWith(".md")) await rm(path.join(outputDir, name), { force: true });
  const labels = options.communityLabels ?? Object.fromEntries(Object.keys(communities).map((cid) => [Number(cid), `Community ${cid}`]));
  const used = new Set<string>();
  const unique = (base: string): string => {
    let slug = base;
    let n = 2;
    while (used.has(slug)) slug = `${base}_${n++}`;
    used.add(slug);
    return slug;
  };
  let count = 0;
  for (const [cidText, nodes] of Object.entries(communities)) {
    const cid = Number(cidText);
    const label = labels[cid] ?? `Community ${cid}`;
    await writeFile(path.join(outputDir, `${unique(safeFilename(label))}.md`), communityArticle(graph, cid, nodes, label, labels, options.cohesion?.[cid]), "utf8");
    count += 1;
  }
  for (const god of options.godNodes ?? []) {
    if (!graph.nodes.has(god.id)) continue;
    await writeFile(path.join(outputDir, `${unique(safeFilename(god.label))}.md`), godNodeArticle(graph, god.id, labels), "utf8");
    count += 1;
  }
  await writeFile(path.join(outputDir, "index.md"), indexMarkdown(communities, labels, options.godNodes ?? [], graph.numberOfNodes(), graph.numberOfEdges()), "utf8");
  return count;
}
